par(mfrow=c(2,2))	
plot(data_set_filtered$TimeDate, data_set_filtered$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(data_set_filtered$TimeDate, data_set_filtered$Voltage, type = "l", xlab = "dateTimeDate", ylab = "Global Active Power")
plot(data_set_filtered$TimeDate, data_set_filtered$Sub_metering_1, type = "l", col = "black", xlab = "", ylab = "Energy sub metering")
lines(data_set_filtered$TimeDate, data_set_filtered$Sub_metering_2, type="l", col="red")
lines(data_set_filtered$TimeDate, data_set_filtered$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=2, col=c("black", "red", "blue"))
plot(data_set_filtered$TimeDate, data_set_filtered$Global_reactive_power, type = "l", xlab = "dateTimeDate", ylab = "Global Active Power")
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()